apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: n16pkwj4e-python 
  janus-idp.io/tekton: n16pkwj4e-python
  backstage.io/kubernetes-id: n16pkwj4e-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n16pkwj4e-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  